### ISSUE TITLE
releases.json no longer maintained; need new strategy

### ISSUE THREAD

**Issue by tillig** [jonstodle/DotNetSdkHelpers#1]
[As of March 2019, the main `releases.json` for .NET Core is no longer maintained.](https://github.com/dotnet/announcements/issues/87) Instead, they appear to have created a [releases-index.json](https://github.com/dotnet/core/blob/master/release-notes/releases-index.json) which has child JSON documents to retrieve to get the actual list of releases.

Not a huge change, but definitely a new strategy required here to calculate the list of all releases. The SDK helpers are currently not actually showing all the available SDKs.

**Comment by jonstodle** [comment]
Sorry for not responding earlier, but I haven’t had time to look at this before now. I very much appreciate you updating me on this. I’ve released a new version of the tool today and you should be able to grab the new version by running `dotnet tool update -g DotNetSdkHelpers`

**Comment by tillig** [comment]
That's awesome, thanks!
