### ISSUE TITLE
Global Installation is failing. 

### ISSUE THREAD

**Issue by Tanmay2711** [jonstodle/DotNetSdkHelpers#22]
Hi Team,

I am getting below error when intsalling this tool with command
dotnet tool install -g dotnetasdkhelpers
Please check dotnet sdks and runtime installed

![image](https://user-images.githubusercontent.com/48334190/219074566-6faded60-422b-475a-a54a-0e90b194884b.png)

Environment -
Windows 10
x64 bit OS

**Comment by tillig** [comment]
I'm guessing there's a global.json forcing net7 and we don't have net7 as a TFM yet. I can add that.

**Comment by tillig** [comment]
This should be fixed by #23 which I just merged. I'll release that as v4.0.0 shortly.
